# Site settings
title: "HAIL: Handong Artificial Intelligence Laboratory" 
email: "charmgil@handong.edu"
description: > # this means to ignore newlines until "baseurl:"
  Handong Artificial Intelligence Lab (HAIL) is a research group at Handong Global University, dedicated to advancing artificial intelligence and machine learning technologies to address real-world challenges across various industries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "hail.handong.edu" # the base hostname & protocol for your site

# User setting
owner: "Charmgil Hong"
email: "charmgil@handong.edu"
facebook_username:
twitter_username:
github_username: "nth221"
address:
  - line: "Newton Hall #201, #221, Handong Global University"
  - line: "Handong-ro 558, Buk-gu, Pohang"
  - line: "Gyeongbuk 37554, Korea"
  # Feel free to add more lines here 
telephone:
copyright: "Handong Artificial Intelligence Laboratory (HAIL)"

# API settings
google_api_key:

# Build settings
markdown: kramdown