# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: 
facebook_username:
twitter_username:
github_username: "nth221"
address:
  - line: "Newton Hall #201, #221, Handong Global University"
  - line: "Handong-ro 558, Buk-gu, Pohang"
  - line: "Gyeongbuk 37554, Korea"
  # Feel free to add more lines here 
telephone:
copyright: "Handong Artificial Intelligence Laboratory (HAIL)"

# API settings
google_api_key:

# Build settings
markdown: kramdown